Resolving the buffer accessed out of bound issue
quic/fastrpc pull request #86
Opened 2024-10-21 19:26 UTC by anankulk

While packing shared buffer with names of all shared objects present in custom DSP_LIBRARY_PATH , their is a possibility of buffer overflow if the shared object names are exceeding the desired limit.The change makes sure the limit is not exceeded thus avoiding buffer overflow. Also, the buffer was allocated with 1KB memory which might fall short to accomodate all the needed shared object names so, increasing this size to 2KB.

2024-10-29 15:01 UTC, quic-mtharu commented on src/fastrpc_procbuf.c
> +						goto bail;
Please ensure to call closedir(dir) after opendir(path) to prevent a possible resource leak. This is crucial for proper resource management.

2024-11-06 15:27 UTC, quic-mtharu commented on src/fastrpc_procbuf.c
> +	VERIFYC(AEE_SUCCESS == apps_std_getenv(DSP_LIBRARY_PATH, data_paths, ENV_PATH_LEN, &env_list_len), AEE_EGETENV);
instead of fixing the size of ENV_PATH_LEN to 256, Can we read the size of ENV_PATH_LEN by std_strlen(DSP_SEARCH_PATH)+1 and allocate the same amount of memory to data_paths

2024-11-06 15:31 UTC, quic-mtharu commented on src/fastrpc_procbuf.c
>  #define ENV_PATH_LEN 256
Can we define all these macros in [apps_std_internal.h](https://github.com/quic/fastrpc/blob/bdb0bfee62f2210fa92a01b0e8d4132fac0fedea/inc/apps_std_internal.h#L20)
where our DSP_LIBRARY_PATH macro is defined.

2024-11-06 15:37 UTC, quic-mtharu requested changes
Please ensure to call closedir(dir) after opendir(path) to prevent a possible resource leak. This is crucial for proper resource management.

Instead of fixing the size of ENV_PATH_LEN to 256, can we determine the size of ENV_PATH_LEN using strlen(DSP_SEARCH_PATH) + 1 and allocate the same amount of memory to data_paths?

Additionally, consider relocating all macros to the header file.

2024-12-19 09:33 UTC, quic-ekangupt commented
New PR created: https://github.com/quic/fastrpc/pull/113

2024-12-19 09:33 UTC, closed without merging